version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Node.dockerfile
      target: 'dev-stage'
    ports:
      - '3000:3000'
    container_name: nestjs-test
    restart: always
    command: /bin/sh -c "cd /app && npm install && npm run start"
    volumes:
      - './app:/app'
    networks:
      - nestjs

networks:
  nestjs:
      name: nestjs_network