version: '3.7'
services:
  app:
    build:
      args:
        user: node
        uid: 1000
        gid: 1000
      context: .
      dockerfile: Node.dockerfile
      target: 'dev-stage'
    ports:
      - '3000:3000'
    container_name: nestjs-test
    restart: always
    command: /bin/sh -c "chown -R 1000:1000 /app && cd /app && yarn install && yarn start:dev"
    volumes:
      - './app:/app'
    networks:
      - nestjs
  db:
    image: postgres:15.3-bullseye
    container_name: nestjs-test-db
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: 'nestjs_test-usr'
      POSTGRES_PASSWORD: 'nestjs_124713'
      POSTGRES_DB: 'nestjs_test'
    volumes:
      - ./sqldata:/var/lib/postgresql/data
    networks:
      - nestjs
  test-db:
    image: postgres:15.3-bullseye
    container_name: nestjs-test-dbtests
    ports:
      - 5435:5432
    restart: always
    environment:
      POSTGRES_USER: 'nestjs_test-usr'
      POSTGRES_PASSWORD: 'nestjs_124713'
      POSTGRES_DB: 'nestjs_test'
    networks:
      - nestjs

networks:
  nestjs:
      name: nestjs_network